README.md
- Updates BLT documentation location to doc.acquia.com
- Updates versions of VM-related software to currently available.
- Adds recommended Vagrant plugins and versions.
=> DOJ-000: Updates readme to reflect changes to BLT documentation and supporting software.

config/default/field.field.node.total_annual_data.field_equiv_full_time_employees.yml, config/default/field.field.node.total_annual_data.field_full_time_employees.yml, config/default/field.field.node.total_annual_data.field_processing_costs.yml, config/default/field.storage.node.field_equiv_full_time_employees.yml, config/default/field.storage.node.field_full_time_employees.yml, config/default/field.storage.node.field_processing_costs.yml, config/default/node.type.total_annual_data.yml
Creates stub entity type for Annual Totals Data. Also defines a few of the fields provided in the [Component Spreadsheet Guidance document](https://docs.google.com/document/d/18yKI3uOAvEjh_hO90KTd6Z8wpEj1BHfWVGqg-HNHnqQ/edit).
=> FOIA-37: Create stub for Annual Total Data entity.

README.md
- Changes path to BLT docs on docs.acquia.com.
- Adds/updates software required for VM.
=> FOIA-000: Updates readme to reflect BLT doc changes.

blt/blt.yml, drush/sites/foia.site.yml
Updating the Drush aliases to match the latest environments on Acquia Cloud.
=> FOIA-000: Update drush aliases to include UAT environment.

config/default/workflows.workflow.annual_report_workflow.yml
Creates workflow for Total Annual Report content. Includes workflow state and transition definitions.
=> FOIA-8: Creates Annual Report workflow.

onboarding-confirmation.md
As written, the acceptance criteria make this issue dependent on FOIA-40. I have not done that task yet.
=> FOIA-000: Confirm GitHub setup for Benji Fisher

docroot/modules/custom/foia_file/src/Commands/FoiaFileCommands.php, docroot/modules/custom/foia_request/tests/src/Kernel/FoiaRequestTest.php, docroot/modules/custom/foia_webform/tests/src/Kernel/AgencyLookupServiceTest.php
- Fixes PHP (3) comment errors found by PHPCS coding standards test.
- Removes 2 unused display config files for the Total Annual Data content type (stub).
- NOTE: Though passing local yaml:lint tests the empty yml files were rejected by Pipelines YAML tests.
=> FOIA-000: Fixes issues found by PHPCS and YAML Lint tests.

config/default/core.entity_form_display.node.total_annual_data.default.yml, config/default/core.entity_view_display.node.total_annual_data.default.yml
- Readds entity_form_display and entity_view_display configs for Total Annual Data content type.
=> FOIA-37: Bugfix - adds entity form and view display configs.

acquia-pipelines.yml, blt/blt.yml, composer.json, composer.lock, simplesamlphp/config/acquia_config.php, simplesamlphp/config/authsources.php, simplesamlphp/config/config.php, simplesamlphp/metadata/saml20-idp-remote.php, tests/behat/features/Manager.feature, tests/behat/features/Saml.feature, tests/phpunit/phpunit.xml
Because of behat test failures after updating to PHP 7.2, I've reinitialized the SAML configs and hand migrated our customizations to the defaults.
=> SAML Reinitialization and test/build fixes.

composer.lock, config/default/migrate_plus.migration.foia_agency_report.yml, config/default/migrate_plus.migration_group.foia_xml.yml, config/default/user.role.agency_administrator.yml, docroot/modules/custom/foia_upload_xml/config/install/migrate_plus.migration.foia_agency_report.yml, docroot/modules/custom/foia_upload_xml/foia_upload_xml.routing.yml, docroot/modules/custom/foia_upload_xml/src/Form/AgencyXmlUploadForm.php
Add an upload form at `/report/upload`.
=> FOIA 6: upload form

tests/behat/features/AnnualFOIAReportData.feature
Adds behat test scaffold for Annual Report Data content type.
=> FOIA-37: Adds behat test for Annual Report Data content type.

.gitignore, phpdocxconfig.ini
=> FOIA-21: Adds Phpdocx config file to root.

config/default/core.extension.yml, config/default/field.field.node.annual_foia_report_data.field_overall_xib_rec_post_prog.yml, config/default/field.field.paragraph.admin_app_vib.field_total.yml, docroot/modules/custom/foia_autocalc/foia_autocalc.info.yml, docroot/modules/custom/foia_autocalc/foia_autocalc.libraries.yml, docroot/modules/custom/foia_autocalc/foia_autocalc.module, docroot/modules/custom/foia_autocalc/foia_autocalc.routing.yml, docroot/modules/custom/foia_autocalc/foia_autocalc.services.yml, docroot/modules/custom/foia_autocalc/js/autocalc-field.js, docroot/modules/custom/foia_autocalc/src/AutocalcConfig.php, docroot/modules/custom/foia_autocalc/src/AutocalcConfigInterface.php, docroot/modules/custom/foia_autocalc/src/Controller/AutocalcConfigController.php
Creates the `foia_autocalc` module and provides sample configuration for its usage.
=> Foia 44 autocalc fields

docroot/modules/custom/foia_autocalc/js/autocalc-field.js
Enables support for autocalulation of totals for paragraph entities with internal autocalculated totals.
=> FOIA-44: Support chained autocalculation totals

config/default/field.field.node.annual_foia_report_data.field_overall_vb3_ex_7_a.yml, config/default/field.field.node.annual_foia_report_data.field_overall_vb3_ex_7_b.yml, config/default/field.field.node.annual_foia_report_data.field_overall_vb3_ex_7_c.yml, config/default/field.field.node.annual_foia_report_data.field_overall_vb3_ex_7_d.yml, config/default/field.field.node.annual_foia_report_data.field_overall_vb3_ex_7_e.yml, config/default/field.field.node.annual_foia_report_data.field_overall_vb3_ex_7_f.yml
=> FOIA-75: Adds auto calculations to V. B. (3) agency overall fields for variations for Ex. 7.

composer.json, composer.lock, docroot/modules/custom/foia_ui/css/foia_ui.validation.css, docroot/modules/custom/foia_ui/foia_ui.libraries.yml, docroot/modules/custom/foia_ui/foia_ui.module, docroot/modules/custom/foia_ui/js/foia_ui.validation.js
- Installs and implements jQuery Validation library
- Disables node _Save_ button until _Validate_ button is pressed
- Includes several example validation rules
- Adds `lessThanEqualSum` example custom validation method 
- Highlights vertical tabs with validation errors
=> FOIA-30 Adds groundwork for Annual Report client-side validation

config/default/field.field.node.annual_foia_report_data.field_overall_vb1_total.yml, config/default/field.field.node.annual_foia_report_data.field_overall_vb2_total.yml, config/default/field.field.node.annual_foia_report_data.field_overall_vic3_num_relied_up.yml, config/default/field.field.node.annual_foia_report_data.field_overall_viic1_total.yml, config/default/field.field.node.annual_foia_report_data.field_overall_viic2_total.yml, config/default/field.field.node.annual_foia_report_data.field_overall_viic3_total.yml, config/default/field.field.paragraph.statute.field_total_num_relied_by_agency.yml
Addressing issue that were raised with FOIA-75.
=> FOIA-75: Additional fields for autocalc.

docroot/modules/custom/foia_ui/js/foia_ui.validation.js
Simple fix. This must've been broken during some code cleanup.
=> FOIA-30: Restore missing variable assignment for vertical tab highlights.

docroot/modules/custom/foia_ui/js/foia_ui.validation.js
Also removes unused field requirement validation.
=> FOIA-30: Adds VI.B. component validation

config/default/migrate_plus.migration.foia_agency_report.yml, config/default/migrate_plus.migration.foia_vb2.yml, config/default/migrate_plus.migration.foia_vb2_other.yml, config/default/migrate_plus.migration.foia_vic3.yml, config/default/migrate_plus.migration.foia_vic3_other.yml, config/default/migrate_plus.migration_group.foia_component_data_import_subs.yml, docroot/modules/custom/foia_upload_xml/config/install/migrate_plus.migration.foia_agency_report.yml, docroot/modules/custom/foia_upload_xml/config/install/migrate_plus.migration.foia_vb2.yml, docroot/modules/custom/foia_upload_xml/config/install/migrate_plus.migration.foia_vb2_other.yml, docroot/modules/custom/foia_upload_xml/config/install/migrate_plus.migration.foia_vic3.yml, docroot/modules/custom/foia_upload_xml/config/install/migrate_plus.migration.foia_vic3_other.yml, docroot/modules/custom/foia_upload_xml/config/install/migrate_plus.migration_group.foia_component_data_import_subs.yml
- IN-PROGRESS definition for section V. B. (2)
=> FOIA-6: Migration import definitions for final Annual Report Sections

docroot/modules/custom/foia_ui/foia_ui.module
~~I'd like to get the submit handler fixed first otherwise this will impact the ability for UAT and other developers to save edited reports.~~ Resolved by #127!
=> FOIA-30: Attach validation to Annual Report node edit form.

docroot/modules/custom/foia_ui/foia_ui.module, docroot/modules/custom/foia_ui/js/foia_ui.validation.js
Resolves errors with validation on editing annual reports.
=> FOIA-30: Pass node add/edit form IDs to jQuery Validation from module.

docroot/modules/custom/foia_ui/js/foia_ui.validation.js
- FOIA Personnel and Costs IX.
- Agency Overall Total Number of "Full-Time FOIA Staff"
- Agency Overall Processing Costs
=> FOIA-30: IX Validation

docroot/modules/custom/foia_ui/js/foia_ui.validation.js
- Iterate over multiple agency components
- Rewrite validation rule against VI.B. rather than VI.C(2)
=> FOIA-30: Revise VI.B. Administrative Appeals validation.

docroot/modules/custom/node_to_docx/src/NodeToDocxHandler.php
This PR solves the problem of / in node titles interfering with creating of binary files by replacing them with - in the file name.
=> FOIA-81: When generating docx file replace '/' in title with '-'.

docroot/modules/custom/foia_ui/js/foia_ui.validation.js
This PR introduces the `convertNAtoZero()` utility function, which can be used on other custom validation methods.
=> FOIA-90: Add XII.A. component and overall validation.

docroot/modules/custom/foia_ui/js/foia_ui.validation.js
=> FOIA-90: V.A. and V.B.(1) validation

docroot/modules/custom/foia_ui/js/foia_ui.validation.js
- Refactor `convertNAtoZero()` function for reuse and clarity.
- Fix typos in Vi.C.(5)
=> FOIA-132: Treat "<1" as zero in validation.

composer.json, composer.lock
When attempting to edit an XML imported Annual Report Entity Reference Revisions throws the following error:
`Error: Call to a member function hasTranslation() on null in entity_reference_revisions_entity_revision_create() (line 266 of modules/contrib/entity_reference_revisions/entity_reference_revisions.module).`
This is a [known bug](https://www.drupal.org/node/3016233) and has been fixed in the dev version of Entity Reference Revisions. This PR applies the patch to the currently stable version 8.x-1.6. 
Also, for what it's worth, BLT made me run `composer update --lock` before I could commit this fix.
=> FOIA-000: Call to a member function hasTranslation().

composer.json, composer.lock
When viewing an Annual Report node, from time to time, errors in the log similar to the below message appear. There is an issue and patch on Drupal.org, the patch fixes it but the issue was auto closed. It might be a while before this fix gets merged into a stable release. https://www.drupal.org/project/paragraphs/issues/2948778
This PR only contains a patch for Paragraphs that addresses this error.
=> FOIA-000: Paragraphs Call to member function on null.

docroot/modules/custom/foia_ui/js/foia_ui.validation.js
Enhances PR #203 to remove references to section V.A.(1), which doesn't actually exist.
=> FOIA-151: Number of Requests Received in Fiscal Year validation text needs to be corrected

composer.json, composer.lock
Reverts acquia-pso/foia-api-enhancements#204 which should have been applied to the release branch rather than acquia-develop.
=> Revert "FOIA-000: Paragraphs Call to member function on null."

docroot/modules/custom/foia_ui/js/foia_ui.validation.js
This time branched from `release` HEAD w/no merge conflicts 😄
=> FOIA-154: XII.E.(2) component-level validation.

docroot/modules/custom/foia_upload_xml/foia_upload_xml.batch.inc, docroot/modules/custom/foia_upload_xml/src/FoiaUploadXmlBatchImport.php, docroot/modules/custom/foia_upload_xml/src/Form/AgencyXmlUploadForm.php
The file name will now have the year and the ID of the Agency in it.
=> FOIA-139: Unique file names for simulataneous imports.

docroot/modules/custom/foia_upload_xml/foia_upload_xml.batch.inc, docroot/modules/custom/foia_upload_xml/src/Form/AgencyXmlUploadForm.php
You should get an validation message if you attempt to upload and migrate a file while another file is being migrated.
=> FOIA-139: better locking

docroot/modules/custom/foia_ui/css/foia_ui_admin.css, docroot/modules/custom/foia_ui/foia_ui.libraries.yml, docroot/modules/custom/foia_ui/foia_ui.module
This is PR 2 out of 4 PRs for Section 508 accessibility recommendations.
Note: this contrast level meets WCAG AA, but not AAA compliance.
=> FOIA-161: Increase contrast of vertical tabs menu links on report form.

docroot/modules/custom/foia_ui/js/foia_ui.validation.js
* Add date format validation method that is more specific than jquery validation's dateISO validation.
* Add validation method to check that the entered date exists.
* Add validation rules to all date fields on the annual report for that accept text values of n/a or 0.
=> FOIA-12: Date validation.

docroot/modules/custom/foia_ui/js/foia_ui.validation.js
=> FOIA-184: Add isInteger function.

docroot/modules/custom/foia_export_xml/src/ExportXml.php
Moves RequestDispositionTotalQuantity element below NonExemptionDenial element in XML export.
=> FOIA-162: Reorders RequestDispositionTotalQuantity element.

docroot/sites/default/settings.php
This fixes the issue of file path on web clusters on prod.
=> FOIA-187: Adds system file temp path to settings.php.

config/default/migrate_plus.migration.foia_agency_report.yml, config/default/migrate_plus.migration.foia_vic2_nonexemption_denial.yml, docroot/modules/custom/foia_upload_xml/config/install/migrate_plus.migration.foia_agency_report.yml, docroot/modules/custom/foia_upload_xml/config/install/migrate_plus.migration.foia_vic2_nonexemption_denial.yml
=> FOIA-156: Adds 0 values for sections VI.C.1 & 2 overall total and selected missing fields.

docroot/modules/custom/foia_ui/foia_ui.module
This is a quick fix. I will follow-up with a core issue and patch, but leave those aside from this project for now since it will probably undergo multiple iterations.
=> FOIA-191: Change orphaned node authoring meta labels to h4 elements.

docroot/modules/custom/foia_export_xml/src/ExportXml.php
FOIA-196: Fixes reference to section V.B.1's Total field for non-centralized agencies.
=> FOIA-196: Fixes reference to section V.B.1's Total field.

docroot/modules/custom/foia_ui/foia_ui.module
The user-facing change is accomplished by consolidating the annual report
node add and node edit hooks to reduce code duplication.
=> FOIA-195: Override XII.E.(2) field label to say "Appeals" on add form.

config/default/migrate_plus.migration.foia_viid_pending_requests.yml, config/default/migrate_plus.migration.foia_viiib_fee_waiver.yml
* Set's VIII.B & VII.D median and average paragraph fields default value to N/A
=> FOIA-193: Edit default values in XML upload.

docroot/modules/custom/foia_ui/js/foia_ui.validation.js
Follow-up from Slack. Validation is old and incorrect and was conflicting with the auto-calculated value.
=> FOIA-000: Remove X. validation since now autocalculated.

docroot/modules/custom/foia_advcalc/js/advcalc-field.js
- Display _Percentage of Total Costs_ component in decimal format.
- Display _Agency Overall Percentage of Total Costs_ component in decimal format.
=> FOIA-000: Display X. Percentage of Total Costs in decimal format.

docroot/modules/custom/foia_advcalc/js/advcalc-field.js
Also includes a documentation fix.
=> FOIA-201: Revise Advanced Autocalc to use once() for performance

config/default/migrate_plus.migration.foia_agency_report.yml, config/default/migrate_plus.migration.foia_viia_processed_requests.yml, config/default/migrate_plus.migration.foia_viib_processed_requests.yml
* Converts LT1 to <1 in fields that import `ResponseTimeLowestDaysValue` in sections VII.A & B
=> FOIA-193: Convert LT1 to <1 in VII.A & B import.

composer.json, composer.lock
Applies the Drupal 8.8 core patch to number handling found here: https://www.drupal.org/project/drupal/issues/2230909#comment-13094346
=> FOIA-227 hotfix to allow saving of Annual Reports

docroot/modules/custom/foia_advcalc/foia_advcalc.libraries.yml, docroot/modules/custom/foia_ui/foia_ui.libraries.yml
* advcalc_field library
* jquery_validation library
* foia_ui_validation library
* foia_ui_admin library
* foia_ui_utility library
=> FOIA-126: Add js library dependencies.

docroot/modules/custom/foia_advcalc/js/advcalc-field.js, docroot/modules/custom/foia_autocalc/js/autocalc-field.js
Includes work from #308.
- Refactor advanced calculations to use named functions and consistent DOM interactions.
- Reorganize `advcalc-field.js` calculations to prioritize named functions and match field order.
=> FOIA-214: Perform autocalc and advanced calculations on page load.

docroot/modules/custom/foia_export_xml/src/ExportXml.php
- moves date conversion processes to convertDate... helper functions.
- check for invalid input and output "Invalid Date" message to XML.
=> FOIA-234: Fixes bugs in date format checks and output.

docroot/modules/custom/foia_readonly/README.md, docroot/modules/custom/foia_readonly/foia_readonly.module
* Adds a readme file
* Adds to the docblock of the `foia_readonly_disable_node_field` function.
=> FOIA-240: Inline documentation and README for foia_readonly module.

docroot/modules/custom/foia_annual_data_report/README.md, docroot/modules/custom/foia_annual_data_report/src/Form/MemoryLimitForm.php
* Makes changes requested in this PR: https://github.com/acquia-pso/foia-api-enhancements/pull/325
* The original branch for this work is https://github.com/alozie/foia-api-enhancements/tree/FOIA-243-annual-report-doc
=> FOIA-243: Inline documentation and README for foia_annual_report_data module.

docroot/modules/custom/foia_ui/js/foia_ui.validation.js
Implements coding standard on FOIA UI validation JS.
See https://www.drupal.org/docs/develop/standards/javascript/javascript-coding-standards#truefalse
=> FOIA-237: Use strict equality comparison in FOIA UI validation.

docroot/modules/custom/foia_advcalc/README.md, docroot/modules/custom/foia_advcalc/js/advcalc-field.js, docroot/modules/custom/foia_ui/js/foia_ui.utility.js
- Add top level README documentation
- Standardize advanced calc JavaScript conventions 
- Apply Drupal coding standards to advanced calc JavaScript
=> FOIA-242: Document FOIA Advanced Auto Calculations module.

docroot/modules/custom/foia_ui/README.md, docroot/modules/custom/foia_ui/foia_ui.module, docroot/modules/custom/foia_ui/js/foia_ui.utility.js, docroot/modules/custom/foia_ui/js/foia_ui.validation.js
- Add `README.md`.
- Fix typos and update docblock.
- Minor code cleanup.
=> FOIA-237: Inline documentation and README for foia_ui module.

docroot/modules/custom/foia_export_xml/src/ExportXml.php
* Do not output empty OldItem values (where date is n/a and days is not an integer or <1)
* Sets integer element default values to 0 if the value is null or n/a.
=> FOIA-229: Export schema changes.

docroot/modules/custom/foia_export_xml/src/ExportXml.php
* Sets decimal and PercentageType element default values to 0.0000
=> FOIA-229: Fix decimal elements default export value.

docroot/modules/custom/foia_ui/js/foia_ui.validation.js
Revert the strict comparisons in foia_ui.validation.js introduced
in a5e216cca113e894d922ac77829ea02e8ca54c29.
=> FOIA-286: Revert strict comparisons in validation.

config/default/core.entity_form_display.media.audio_file.default.yml, config/default/core.entity_form_display.media.audio_file.media_browser.yml, config/default/core.entity_form_display.media.video.default.yml, config/default/core.entity_form_display.media.video.media_browser.yml, config/default/core.entity_form_display.media.video_file.default.yml, config/default/core.entity_form_display.media.video_file.media_browser.yml, config/default/core.entity_view_display.media.audio_file.default.yml, config/default/core.entity_view_display.media.audio_file.embedded.yml, config/default/core.entity_view_display.media.audio_file.media_library.yml, config/default/core.entity_view_display.media.audio_file.thumbnail.yml, config/default/core.entity_view_display.media.video.default.yml, config/default/core.entity_view_display.media.video.embedded.yml, config/default/core.entity_view_display.media.video.thumbnail.yml, config/default/core.entity_view_display.media.video_file.default.yml, config/default/core.entity_view_display.media.video_file.embedded.yml, config/default/core.entity_view_display.media.video_file.thumbnail.yml, config/default/core.extension.yml, config/default/field.field.media.audio_file.field_media_audio_file.yml, config/default/field.field.media.audio_file.field_media_in_library.yml, config/default/field.field.media.video.field_media_in_library.yml, config/default/field.field.media.video.field_media_video_embed_field.yml, config/default/field.field.media.video_file.field_media_in_library.yml, config/default/field.field.media.video_file.field_media_video_file.yml, config/default/field.storage.media.field_media_audio_file.yml, config/default/field.storage.media.field_media_video_embed_field.yml, config/default/field.storage.media.field_media_video_file.yml, config/default/lightning_core.versions.yml, config/default/media.type.audio_file.yml, config/default/media.type.video.yml, config/default/media.type.video_file.yml
* Updates config for the video and video_file media types defined in `lightning_media_video`.  Adds a `field_media_video_file` field to the video_file media type
* Enables the `lightning_media_audio` module, adding a `field_media_audio_file` field to the audio_file media type.  Recreates and exports the audio_file media type with default config.
=> Foia-000: Update lightning media module config.

config/default/jsonapi_extras.jsonapi_resource_config.node--annual_foia_report_data.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--admin_app_via.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--admin_app_vib.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--admin_app_vic1.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--admin_app_vic2.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--admin_app_vic3.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--admin_app_vic3_oth_details.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--admin_app_vic4.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--fees_x.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--foia_pers_costs_ix.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--foia_req_va.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--foia_req_vb1.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--foia_req_vb2.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--foia_req_vb2_other_details.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--foia_req_vb3.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--foia_xii_backlogged.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--foia_xii_received_proc.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--foia_xiia.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--foia_xiib.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--oldest_days.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--pending_requests_viid.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--proc_req_viic.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--processed_requests_vii.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--req_viiia.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--req_viiib.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--statute.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--statute_agency_details.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--sub_xia.yml, config/default/jsonapi_extras.jsonapi_resource_config.paragraph--sub_xib.yml
Configures an /api/annual_foia_report endpoint with jsonapi, includes
all paragraph items and configures the paragraph item resource
responses.
=> FOIA-258: Configure annual report api resources.
