- docroot/modules/custom/foia_webform/foia_webform.info.yml
Without this change, 'drush config-import' tries to enable foia_webform
before webform. This leads to an error because of a missing service.
> FOIA-38: Add a missing dependency.

- blt/blt.yml
When running `blt sync` to pull from UAT, I'm seeing the following error when it tries to sanitize users:
```
In Statement.php line 59:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'drupal.taxonomy_
term__scheduled_transition_date' doesn't exist
```
This avoids that issue by setting the sanitize option to false. It's a hack to unblock us for now. We will need a longer term solution to the root issue at some point in the future.
> FOIA-000: Setting sanitize to false to avoid blt sync issue.

- blt/blt.yml
It's unclear why ACSF is in the uninstall list since we don't use it. Looking at `git blame`, it's been there forever. I'm seeing it result in intermittent failures when running a `blt sync` though. Taking it out.
> FOIA-000: Remove ACSF from uninstall list since we're not using it.

- docroot/modules/custom/foia_autocalc/js/autocalc-field.js
In particular, this allows "n/a" to be used on XII.A. `field_back_app_end_yr` and still auto-calculate `overall_xiia_back_app_end_yr` by treating that value as 0, instead of displaying `NaN`.
> FOIA-44: Treat non-numeric fields as 0 for autocalc.

- config/default/core.extension.yml
- docroot/modules/custom/foia_export_xml/composer.json
- docroot/modules/custom/foia_export_xml/foia_export_xml.info.yml
- docroot/modules/custom/foia_export_xml/foia_export_xml.links.task.yml
- docroot/modules/custom/foia_export_xml/foia_export_xml.routing.yml
- docroot/modules/custom/foia_export_xml/src/Controller/ExportController.php
- docroot/modules/custom/foia_export_xml/src/ExportXml.php
This handles routing, adding a tab to the node page, and so on. It returns a simple, but valid, XML file.
> FOIA-68: Download an XML file for the annual report.

- docroot/modules/custom/foia_ui/js/foia_ui.validation.js
I confirmed this expectation with Karen and Bobby on a call today. The rationale is that if min and max values are the same number, it should still pass validation.
> FOIA-30: Change betweenminmaxcomp validation method to ≥ min and ≤ max.

- config/default/migrate_plus.migration.foia_agency_report.yml
- config/default/migrate_plus.migration.foia_iv_details.yml
- config/default/migrate_plus.migration.foia_iv_statute.yml
- docroot/modules/custom/foia_upload_xml/config/install/migrate_plus.migration.foia_agency_report.yml
- docroot/modules/custom/foia_upload_xml/config/install/migrate_plus.migration.foia_iv_details.yml
- docroot/modules/custom/foia_upload_xml/config/install/migrate_plus.migration.foia_iv_statute.yml
- docroot/modules/custom/foia_upload_xml/src/Plugin/migrate/process/FilterValues.php
~This is totally untested and incomplete, so do not merge yet.~
Update: ready to roll.
One caveat: there is an unanswered question on FOIA-6. Depending on the answer, we may need to modify this code.
> I notice that `field_case_citation` on the Statute paragraph type is limited to 255 characters, but the sample XML file (USDA 2018) includes this entry:
> ...
> I believe that is 342 characters, 344 bytes. Should we truncate the text during import or should we change the definition of that field?
> FOIA-6: Import data from Section IV of the XML report.

- docroot/modules/custom/foia_ui/js/foia_ui.validation.js
- Allows new annual report nodes to be submitted.
- Now validates fields on inactive vertical tabs.
- Disables validation when saving.
> FOIA-30: Remove jQuery Validation debugging code.

- docroot/modules/custom/foia_ui/js/foia_ui.validation.js
The alert messages are a nuisance when displayed more than once. Ultimately, the problem is that the `invalidhandler` is getting invoked more than once, but until that issue is resolved, this is an interim usability improvement.
> FOIA-30: Disables validation alert messages.

- docroot/modules/custom/foia_ui/js/foia_ui.validation.js
The change to the "lessThanEqualToNA" method, adding the .val() to the param at the top, was a result of testing when two subsequent fields both had "n/a".  It should apply to the other validation fields using this method also.
> FOIA-90: Rules for XII C

- config/default/field.field.node.annual_foia_report_data.field_overall_viid_comp_pend.yml
- config/default/field.field.node.annual_foia_report_data.field_overall_viid_exp_pend.yml
- config/default/field.field.node.annual_foia_report_data.field_overall_viid_sim_pend.yml
- config/default/field.field.node.annual_foia_report_data.field_overall_viiia_num_jud_w10.yml
- config/default/field.storage.node.field_overall_viiia_num_jud_w10.yml
Note that the change to `config/default/field.storage.node.field_overall_viiia_num_jud_w10.yml` does not reflect an explicit change to the field I made but rather was changed via export of config from Drupal.
> FOIA-88: Add calculations to VII.D and VIII.A

- composer.json
- composer.lock
- docroot/modules/custom/foia_readonly/foia_readonly.module
- patches/FOIA-96-readonly-inputs.patch
This corrects a failure with my initial FOIA-96 work, which set the fields to disabled rather than readonly.  Unfortunately this change costs us the default styling of disabled fields.
> FOIA-96: Changing disabled attribute to readonly.

- docroot/modules/custom/foia_ui/js/foia_ui.validation.js
- Does not require checkbox elements, which are assumed to be optional.
- Performs some sleight-of-hand with select option values for "- None -" to avoid a hard require.
- Excludes revision log message from required validation.
- Auto-calculated fields are disabled and therefore not required.
> FOIA-95 Soft-require all Annual Report fields.

- docroot/modules/custom/foia_ui/js/foia_ui.validation.js
This approach might have a slight performance improvement when loading the initial validation rules as well since it now limits the required select drop-down work-around to when the validation button is clicked.
> FOIA-95: Revise handling of invalid select drop-downs for AJAX.

- box/doj/README.md
- box/doj/vm-setup.sh
- drush/sites/foia.site.yml
I just went through the provision process again, and these tweaks were needed.
To explain the drush alias: We're forced to use drush inside the VM, because we don't have PHP on our computers.
> DOJ-specific VM updates

- config/default/core.extension.yml
- config/default/lightning_core.versions.yml
- docroot/modules/custom/foia_advcalc/foia_advcalc.info.yml
- docroot/modules/custom/foia_advcalc/foia_advcalc.libraries.yml
- docroot/modules/custom/foia_advcalc/foia_advcalc.module
- docroot/modules/custom/foia_advcalc/js/advcalc-field.js
- docroot/modules/custom/foia_ui/js/foia_ui.validation.js
Currently adds custom auto-calculations for fields on the following sections:
- V.A. (req_pend_start_yr)
- VI.A. (app_pend_end_yr)
- X. (overall_x_perc_costs - code moved from foia_ui.validation.js)
- XII. B. (pend_end_yr)
In Progress:
Calculation of X. perc_costs = IX. proc_costs / X. total_fees
> FOIA-117: Adds Advanced Auto-Calc functionality for specific fields.

- docroot/modules/custom/node_to_docx/templates/docx-agency-component-abbrev.html.twig
The variable printing out the abbreviation was not being incremented with the loop variable -- good catch by Barrett.
> FOIA-148: Fix to abbreviations table.

- config/default/core.entity_form_display.node.annual_foia_report_data.default.yml
- config/default/core.entity_form_display.paragraph.admin_app_vic4.default.yml
- config/default/core.entity_view_display.node.annual_foia_report_data.default.yml
- config/default/core.entity_view_display.paragraph.admin_app_vic4.default.yml
- config/default/field.field.node.annual_foia_report_data.field_overall_vic4_avg_num_days.yml
- config/default/field.field.node.annual_foia_report_data.field_overall_vic4_high_num_days.yml
- config/default/field.field.node.annual_foia_report_data.field_overall_vic4_low_num_days.yml
- config/default/field.field.node.annual_foia_report_data.field_overall_vic4_med_num_days.yml
- config/default/field.field.paragraph.admin_app_vic4.field_avg_num_days.yml
- config/default/field.field.paragraph.admin_app_vic4.field_high_num_days.yml
- config/default/field.field.paragraph.admin_app_vic4.field_low_num_days.yml
- config/default/field.field.paragraph.admin_app_vic4.field_med_num_days.yml
- config/default/field.storage.node.field_overall_vic4_avg_num_days.yml
- config/default/field.storage.node.field_overall_vic4_high_num_days.yml
- config/default/field.storage.node.field_overall_vic4_low_num_days.yml
- config/default/field.storage.node.field_overall_vic4_med_num_days.yml
- config/default/field.storage.paragraph.field_avg_num_days.yml
- config/default/field.storage.paragraph.field_high_num_days.yml
- config/default/field.storage.paragraph.field_low_num_days.yml
- config/default/field.storage.paragraph.field_med_num_days.yml
- docroot/modules/custom/foia_ui/js/foia_ui.validation.js
I deleted the fields in question and then re-recreated them with the same machine names.  The validation JS had to be updated to handle "<1" as well.   Tested on a fresh DB from blt sync to make sure the configs were importing OK.
> FOIA-164: Switch VI.C(4) field to text to allow for <1.

- docroot/modules/custom/foia_upload_xml/src/Form/AgencyXmlUploadForm.php
This seems to block the ability to launch a migration if one is already running.  It's possible that by perfect timing they could still do it, but it seems to have reduced the window to nearly impossible.
> FOIA-139: Block simultaneous submissions at the form level.

- docroot/modules/custom/foia_upload_xml/src/Form/AgencyXmlUploadForm.php
It will no longer lock when you just select the file to upload.
> FOIA-139: Only set the lock on submit of form, not on upload of file.

- docroot/modules/custom/foia_annual_data_report/config/install/foia_annual_data_report.settings.yml
- docroot/modules/custom/foia_annual_data_report/foia_annual_data_report.links.menu.yml
- docroot/modules/custom/foia_annual_data_report/foia_annual_data_report.module
- docroot/modules/custom/foia_annual_data_report/foia_annual_data_report.routing.yml
- docroot/modules/custom/foia_annual_data_report/src/Form/MemoryLimitForm.php
Using array_unshift to get our submit function to run in front of core's feels skeevy, but it works; as implemented, it even fires before [hook_entity_presave()](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21entity.api.php/function/hook_entity_presave/8.2.x).
What still needs to be addressed is increasing it when loading the entity in either view or edit modes.
> FOIA-178: Increase memory limit on Annual Reports.

- docroot/modules/custom/foia_ui/css/foia_ui.validation.css
- docroot/modules/custom/foia_ui/js/foia_ui.validation.js
* Displays an overlay on the node form while the validator is running.  
* Moves the `valid()` call into a timeout so that the overlay has time to render before the validation starts running.  The overlay (or a throbber) won't display otherwise.
> FOIA-143: Display overlay when validating.

- docroot/modules/custom/foia_ui/js/foia_ui.validation.js
Include convertSpecialToZero method in equalToLowestComp and
equalToHighestComp validations, making values of <1 equivalent to 0.
> FOIA-167: Let low and high value comps accept <1.

- docroot/modules/custom/foia_ui/js/foia_ui.validation.js
Ensure that validation overlay does not get added again when new
paragraph components are added.
> FOIA-185: Add validation overlay only once.

- docroot/modules/custom/foia_ui/js/foia_ui.validation.js
Adds per agency/component validation for the Oldest Days paragraph type in the following sections
- VI.C.(5). TEN OLDEST PENDING ADMINISTRATIVE APPEALS
- VII.E. PENDING REQUESTS
- XII.C. CONSULTATIONS ON FOIA REQUESTS
> FOIA-169: Order of 10 Oldest per component validation

- config/default/core.entity_form_display.node.annual_foia_report_data.default.yml
- docroot/modules/custom/foia_ui/js/foia_ui.validation.js
* Removes unhighlight and highlight functions
* Adds a showErrors method to the validator that runs the defaultShowErrors, then highlights all top level tab items at once
* Adds the `once()` method to the validate button click handler, ensuring validation runs once
* Adds a class to the form's main tab group for better targeting the top level vertical tabs in js.
> Foia 200 validation js performance

- docroot/modules/custom/foia_advcalc/js/advcalc-field.js
- This PR also includes some indentation and whitespace cleanup of `advcalc-field.js` so you may wish to review individual commits.
- "<1" is treated as 0.1 for comparisons and overall values between 0 and 1 display as "<1"
- "n/A" is excluded from auto-calculations.
-  Invalid text inputs have empty overall value instead of displaying "NaN".
> FOIA-175: Autocalc for VI.C.4, VII.A, VII.B, and VIII.A

- config/default/user.role.agency_administrator.yml
- config/default/user.role.agency_manager.yml
- config/default/views.view.agency_component_by_agency.yml
- Removes the "published = YES" filters on the _Agency/Component by Agency_ entity reference view.
- Grants _Agency Manager_ permission to access unpublished _Agency Component_ nodes.
- Grants _Agency Administrator_ permission to access unpublished _Agency Component_ nodes.
> FOIA-205 Include unpublished agency components - Hotfix

- docroot/modules/custom/foia_annual_data_report/foia_annual_data_report.libraries.yml
- docroot/modules/custom/foia_annual_data_report/foia_annual_data_report.module
- docroot/modules/custom/foia_annual_data_report/js/foia-change-report-agency.js
The change event was not firing in IE11 when a new value for
field_agency was selected from the autocomplete drop down.  To work
around this, listen for a blur event on that field and fire a custom
change event if the value has changed.
> FOIA-202: Refresh report in IE on agency change.

- docroot/modules/custom/foia_advcalc/js/advcalc-field.js
- docroot/modules/custom/foia_autocalc/js/autocalc-field.js
-  Output overall as "N/A" on V1.C.4, VII.A, VII.B, VII.D. when all source fields  are "N/A".
- Remove duplicate advanced auto-calculation for _VIII.A Agency Overall Number Adjudicated Within Ten Calendar Days_. It is now handled only by existing `foia_autocalc` configuration.
- Add support to `foia_autocalc` module to treat "N/A" values as Null.
- Add support to `foia_autocalc` module to output total as "N/A" when all source field values are "N/A".
> FOIA-175: Output "N/A" to auto-calculated field when all source fields are "N/A"

- docroot/modules/custom/foia_ui/js/foia_ui.validation.js
Remove the requirement that the Validate button is clicked in order to
save an annual report form.  This fixes the issue where the save button
is disabled again if the form autosaves or a paragraph component is
added.
> FOIA-197: Don't disable save on report node forms.

- composer.json
- composer.lock
- config/default/auto_entitylabel.settings.node.annual_foia_report_data.yml
- config/default/core.extension.yml
- docroot/modules/custom/foia_annual_data_report/foia_annual_data_report.module
- tests/behat/features/Administrator.feature
- tests/behat/features/AnnualFOIAReportData.feature
* Makes annual report node titles uneditable by users
* Automatically titles annual report nodes as `{{Agency Term Abbreviation}} - {{Annual Report Year Field}} - Annual FOIA Report`
* Updates the title if field data changes.
* Uses the Agency term's abbreviation field since the node's agency field is required (as opposed to the node's Agency Abbreviation field).
* Sets the default value of the nodes FOIA Annual Report Year field to the current year, if a value does not already exist.
* Removes filling out the title in the `Administrator.feature` behat test scenario `Agency Administrator can save Annual FOIA Reports in all workflow
states`
* Removes filling out the title in the `AnnualFOIAReportData.feature` behat test scenario `Create an Annual FOIA Report Data node.` and checks that the …
> Foia 145 automatic entity label

- docroot/modules/custom/foia_autocalc/js/autocalc-field.js
After an initial attempt to limit the calculations to empty fields, I decided to keep the code simpler and I haven't observed much of a performance impact.
> FOIA-214: Perform autocalculations when annual report form is loaded.

- docroot/modules/custom/foia_upload_xml/foia_upload_xml.services.yml
- docroot/modules/custom/foia_upload_xml/src/EventSubscriber/FoiaUploadXmlMigrationSubscriber.php
* Adds a presave event that acts on the foia_agency_report migration.
* Finds report node ids that match the upload file's report year and
agency abbreviation and updates the migrate_map_foia_agency_report table
if it does not match the existing node id.
> FOIA-217: Add migration pre save event listener.

- docroot/modules/custom/foia_advcalc/foia_advcalc.info.yml
- docroot/modules/custom/foia_advcalc/js/advcalc-field.js
- docroot/modules/custom/foia_ui/foia_ui.libraries.yml
- docroot/modules/custom/foia_ui/foia_ui.module
- docroot/modules/custom/foia_ui/js/foia_ui.utility.js
- docroot/modules/custom/foia_ui/js/foia_ui.validation.js
- Refactors and consolidates code use across `foia_ui.validate.js` and `advcalc-field.js`.
- Enables strict mode
- Updates and improves documentation
- Some whitespace cleanup
Note that after rewriting the _for i_ loops on object collections with Object.keys.forEach(), I ran encountered errors with the final item in the array and I did not find that the code was more readable, so I opted to keep the initial _for i_ loop approach.
> FOIA-126 validation (and advanced autocalc) code cleanup

- docroot/modules/custom/node_to_docx/templates/docx-iv-exemption-3-statutes.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-ix-foia-personnel-costs.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-va-foia-requests.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-vb3-disposition-number-of-times.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-via-administrative-appeals.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-vic3-reasons-other.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-vic4-response-time.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-vic5-ten-oldest-pending.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-viia-response-time.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-viib-processed-requests-response-time.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-viic-processed-complex-ten-day.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-viic-processed-expedited-ten-day.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-viic-processed-simple-ten-day.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-viid-pending-requests.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-viie-pending-requests-ten-oldest.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-viiia-requests-expedited.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-viiib-requests-fee-waiver.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-x-fees-collected.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-xia-number-times-subsection-c.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-xib-number-times-subsection-a2.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-xiia-backlogs.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-xiib-consultations.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-xiic-consultations-ten-oldest.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-xiid-comparisons-backlogged.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-xiid-comparisons.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-xiie-comparisons-appeals.html.twig
- docroot/modules/custom/node_to_docx/templates/docx-xiie2-comparisons-backlogged-appeals.html.twig
* Fixes footnote table cell widths in docx templates for footnote cells that don't have a width set.
* Fixes broken markup in docx templates
* Normalizes footnote table cell widths to 570
* Standardizes footnote text alignment.
> Foia 231 docx footnote width

- docroot/modules/custom/foia_ui/js/foia_ui.validation.js
I'm not absolutely sure that this validation should be removed, but the following fields are now auto-calculated and read-only, so it appears to be obsolete.
See https://acquiaps.atlassian.net/browse/FOIA-220
> Agency Overall high and low fields autocalc and do not have validation on them; however, they should be correct is all component high and low fields are correct. Verify this.
- Agency Overall Lowest Number of Days
- Agency Overall Highest Number of Days
- Simple - Agency Overall Lowest Number of Days
- Simple - Agency Overall Highest Number of Days
- Complex - Agency Overall Lowest Number of Days
- Complex - Agency Overall Highest Number of Days
- Expedited Processing - Agency Overall Lowest Number of Days
- Expedited Processing - Agency Overall Highest Number of Days
- Simple - …
> FOIA-126 Remove obsolete validation on VI.C(4), VII.A., and VII.B.

- config/default/field.field.node.annual_foia_report_data.field_overall_x_perc_costs.yml
- config/default/field.field.paragraph.fees_x.field_perc_costs.yml
* Sets a minimum value of 0 for paragraph and agency overall percentage fields in section X.
* Sets a maximum value of 1 for paragraph and agency overall percentage fields in section X.
Notes: 
* Setting the percentage fields min and max values to 0 and 1, respectively does not change the ability to import those values.  Importing xml files with values in those fields that are greater than 1 still imports the node and the field value.  I would assume that this is correct b/c we would value importing data so it can be changed later over attempting to correct invalid data.  If that is not the case, we need to do more work to manage these values within the import process.
* The min/max values do mean that saving a node with values greater than 1 (or less than 0) would cause Drupal errors and …
> FOIA-229: Set percentage field min/max of 0 & 1.

- composer.json
- composer.lock
- config/default/action.settings.yml
- config/default/core.extension.yml
- config/default/lightning_core.versions.yml
- config/default/system.action.change_moderation_state_of_content.yml
- patches/FOIA-32-validator.patch
- Applies core patch to add bulk actions for content moderation changes
- Adds and enables _Publish_ bulk content moderation action
- Applies core patch to not generate error message on empty Agency/Component entity reference validation.
- Includes and applies custom core patch to exclude Agency/Component entity reference from validation errors (due to contextual filter argument from content URL).
> FOIA-32: Batch publish Annual Report.

- docroot/modules/custom/foia_ui/js/foia_ui.validation.js
Allows report validation to continue processing for other paragraphs in section despite hitting missing agency component.
> FOIA-173: Add return value to agency component check.

- config/default/views.view.content.yml
* Adds the human readable moderation state as a hidden field in the admin/content view
* Displays the human readable moderation state in the Status column of the admin/content view
The method of using a hidden field and rewriting the Status column with the value in the hidden field  is being used because sorting the status column was failing when only using the human readable field value.  I believe this is because using only the human readable field did not use the content moderation state relationship, so couldn't get values for the field on nodes that were not Annual Report Data nodes.
> FOIA-230: Use human readable state in admin view.

- docroot/modules/custom/foia_upload_xml/README.md
* Add information about queue processing and troubleshooting
* Add detail to the section about referencing component data in the agency report migration
* Reorganize "Running the migrations" back into the troubleshooting section as it appears that was the original intent.
> FOIA-238: Inline documentation and README for foia_upload_xml module.

- config/default/jsonapi_extras.jsonapi_resource_config.node--agency_component.yml
- config/default/user.role.anonymous.yml
- docroot/modules/custom/foia_api/foia_api.module
* Gives users access to view any unpublished agency component
in order to satisfy the requirement that unpublished
agency_component nodes are accessible via the api.
* Includes the status field in the agency_component endpoint
in order to allow filtering by status in the request.
* Gives users access to view any field_rep_start value in order
to allow filtering by field_rep_start values in an agency component
request.
* Gives access to jsonapi to filter from all nodes in order to allow
access to unpublished agency components via the api.
> FOIA-312: Allow viewing unpublished agency components.

- docroot/modules/custom/foia_api/foia_api.module
Some numeric values are stored in the database as string fields so that
the special values 'N/A' and '<1' can be used in those fields.  In order
to properly compare values during api requests, check if the value in
the database is numeric and cast it to an integer if it is being
compared to a numeric value.
> FOIA-359: Cast string fields when numeric.

- docroot/modules/custom/foia_upload_xml/composer.json
- docroot/modules/custom/foia_upload_xml/drush.services.yml
- docroot/modules/custom/foia_upload_xml/src/Commands/FoiaUploadXmlCommands.php
* Adds a drush command to bulk import a directory of report xml files.
* `drush foia-upload-xml:bulk-upload path/to/report/files` OR `drush foia-upload-xml:bulk-upload /absolute/path/to/report/files`
* includes command alias `drush fuxml path/to/report/files`
> FOIA-368: Bulk report xml uploader.

- docroot/modules/custom/foia_upload_xml/foia_upload_xml.services.yml
- docroot/modules/custom/foia_upload_xml/src/EventSubscriber/FoiaUploadXmlMigrationPostImportSubscriber.php
- docroot/modules/custom/foia_upload_xml/src/FoiaUploadXmlMigrateExecutable.php
* Adds information about the report that failed to be imported to the migration class.
* In the POST_IMPORT event, saves the data that has been processed to the node.
* After partially importing the report, sets the report node moderation state to draft.
> FOIA-369: Create node on failure.

- docroot/modules/custom/foia_upload_xml/foia_upload_xml.services.yml
- docroot/modules/custom/foia_upload_xml/src/EventSubscriber/FoiaUploadXmlPostImportCalculationsSubscriber.php
* Adds an event listener for the `PRE_ROW_SAVE` event, which will calculate statute totals for each row imported during the `foia_iv_statute` migration.
> FOIA-371: Calculate section IV statute totals.

- config/default/jsonapi_extras.jsonapi_resource_config.node--agency_component.yml
* Adds a default status filter to the agency_component jsonapi endpoint, limiting
returned agency components to published nodes only.
> FOIA-000: Add default status to component api.
